apiVersion: v2
name: bestrong-api
description: API with Canary support
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 18.2.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled