apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubecost-ingressroute
  namespace: kubecost
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kubecost-bestrongteam2.duckdns.org`)
      kind: Rule
      middlewares:
        - name: kubecost-auth
      services:
        - name: kubecost-cost-analyzer
          port: 9090
  tls:
    secretName: kubecost-tls-duckdns