apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecost-bestrong-cert
  namespace: kubecost
spec:
  secretName: kubecost-tls-duckdns 
  dnsNames:
    - kubecost-bestrongteam2.duckdns.org
  issuerRef:
    name: selfsigned-issuer 
    kind: ClusterIssuer