apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-kubecost-secure
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kubecost-bestrongteam2.duckdns.org`)
    kind: Rule
    services:
    - name: kubecost-cost-analyzer  
      namespace: kubecost           
      
      port: 9090
  tls:
    secretName: {{ .Release.Name }}-kubecost-tls-duckdns