apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-kubecost-secure-route
  namespace: kubecost
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kubecost-bestrongteam2.duckdns.org`)
    kind: Rule
    services:
    - name: kubecost-cost-analyzer 
      port: 9090
  tls:
    secretName: bestrong-prod-kubecost-tls-duckdns