apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-kubecost-cert
  namespace: kubecost
spec:
  secretName: {{ .Release.Name }}-kubecost-tls-duckdns
  dnsNames:
    - kubecost-bestrongteam2.duckdns.org
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
